name: Road to Demo

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Check coding standards
        run: dotnet format --verify-no-changes
  
      - name: Test UnitTests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage/UnitTests Tests/UnitTests/UnitTests.csproj
  
      - name: Test RegressionTests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage/RegressionTests Tests/RegressionTests/RegressionTests.csproj
  
      - name: Code Coverage Summary Report for UnitTests
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/UnitTests/**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'
  
      - name: Code Coverage Summary Report for RegressionTests
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/RegressionTests/**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'
  
      - name: Combine Coverage Summaries
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
  
          echo "# Unit Tests Coverage" > combined-coverage-summary.md
          reportgenerator -reports:coverage/UnitTests/**/coverage.cobertura.xml -targetdir:CodeCoverage/UnitTests -reporttypes:MarkdownSummary
          cat CodeCoverage/UnitTests/Summary.md >> combined-coverage-summary.md
  
          echo "# Regression Tests Coverage" >> combined-coverage-summary.md
          reportgenerator -reports:coverage/RegressionTests/**/coverage.cobertura.xml -targetdir:CodeCoverage/RegressionTests -reporttypes:MarkdownSummary
          cat CodeCoverage/RegressionTests/Summary.md >> combined-coverage-summary.md
  
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: combined-coverage-summary.md
  
      - name: Write to Job Summary
        run: cat combined-coverage-summary.md >> $GITHUB_STEP_SUMMARY

      - name: Deploy to Testing Environment
        # # Add deployment steps here, such as deploying to a testing environment
        # # Example: Use SSH or FTP to deploy to a testing server
        # # Note: Replace the placeholders with your deployment commands
        # run: |
        #   ssh user@example.com "cd /path/to/deployment && git pull origin release && dotnet publish -o published_folder"
        #   # Example: Restarting the application after deployment
        #   ssh user@example.com "sudo systemctl restart your-application.service"
        run: echo "Deployment to testing environment completed successfully!"