name: Road to Integration

on:
  pull_request:
    branches: 
      - 'integration*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Check coding standards
      run: dotnet format --verify-no-changes

    - name: Clean up old coverage files
      run: rm -rf coverage/*

    - name: Run unit tests with coverage
      run: dotnet test ./Tests/UnitTests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage/unit

    - name: Run regression tests with coverage
      run: dotnet test ./Tests/RegressionTests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage/regression

    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Merge coverage reports
      run: |
        reportgenerator -reports:"coverage/unit/**/coverage.cobertura.xml;coverage/regression/**/coverage.cobertura.xml" -targetdir:coverage/merged
      env:
        PATH: $PATH:/home/runner/.dotnet/tools

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/merged/index.html
        badge: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md