name: Road to Integration

on:
  pull_request:
    branches: [ "integration" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Check coding standards
      run: dotnet format --verify-no-changes

    - name: Unit test
      run: |
        dotnet test ./tests/UnitTests --no-build --verbosity normal > unit_test.log || true
        grep -v "Testhost process for source(s).* exited with error: Error: An assembly specified in the application dependencies manifest (testhost.deps.json) was not found" unit_test.log 

    
