name: Road to Deployment

on:
  workflow_dispatch:

jobs:
  scan-for-vulnerability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Vulnerability Scan
        run: |
          # Run Burp Suite vulnerability scan commands here
          # Example: burpsuite-cli scan -t https://example.com -o result.xml
          echo "Vulnerability scan completed successfully!"

  build-and-package:
    runs-on: ubuntu-latest
    needs: [scan-for-vulnerability]
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Package Repository
        run: zip -r repository.zip .
    
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
            name: repository
            path: repository.zip