name: Road to Demo

on:
  workflow_dispatch:

jobs:
  coding-standard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Check coding standards
        run: dotnet format --verify-no-changes
  
  unit-test:
    runs-on: ubuntu-latest
    needs: [coding-standard]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
  
      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --no-restore 

      - name: Test UnitTests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage/UnitTests Tests/UnitTests/UnitTests.csproj

      - name: Code Coverage Summary Report for UnitTests
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/UnitTests/**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Generate Coverage Summary for UnitTests
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          echo "# Unit Tests Coverage" > unit-coverage-summary.md
          reportgenerator -reports:coverage/UnitTests/**/coverage.cobertura.xml -targetdir:CodeCoverage/UnitTests -reporttypes:MarkdownSummary
          cat CodeCoverage/UnitTests/Summary.md >> unit-coverage-summary.md

      - name: Add Unit Test Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: unit-test
          recreate: true
          path: unit-coverage-summary.md

      - name: Write Unit Test Coverage to Job Summary
        run: cat unit-coverage-summary.md >> $GITHUB_STEP_SUMMARY

  regression-test:
    runs-on: ubuntu-latest
    needs: [unit-test]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
  
      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --no-restore 

      - name: Test RegressionTests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage/RegressionTests Tests/RegressionTests/RegressionTests.csproj

      - name: Code Coverage Summary Report for RegressionTests
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/RegressionTests/**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Generate Coverage Summary for RegressionTests
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          echo "# Regression Tests Coverage" > regression-coverage-summary.md
          reportgenerator -reports:coverage/RegressionTests/**/coverage.cobertura.xml -targetdir:CodeCoverage/RegressionTests -reporttypes:MarkdownSummary
          cat CodeCoverage/RegressionTests/Summary.md >> regression-coverage-summary.md

      - name: Add Regression Test Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: regression-test
          recreate: true
          path: regression-coverage-summary.md

      - name: Write Regression Test Coverage to Job Summary
        run: cat regression-coverage-summary.md >> $GITHUB_STEP_SUMMARY

  deploy-for-testing:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Deploy to Testing Environment
        # # Add deployment steps here, such as deploying to a testing environment
        # # Example: Use SSH or FTP to deploy to a testing server
        # # Note: Replace the placeholders with your deployment commands
        # run: |
        #   ssh user@example.com "cd /path/to/deployment && git pull origin release && dotnet publish -o published_folder"
        #   # Example: Restarting the application after deployment
        #   ssh user@example.com "sudo systemctl restart your-application.service"
        run: echo "Deployment to testing environment completed successfully!"