name: Road to Demo

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Check coding standards
        run: dotnet format --verify-no-changes
  
      - name: Clean up old coverage files
        run: rm -rf coverage/*

      - name: Run unit tests with coverage
        run: dotnet test ./Tests/UnitTests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage/unit
  
      - name: Run regression tests with coverage
        run: dotnet test ./Tests/RegressionTests --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage/regression

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/unit/**/coverage.cobertura.xml, coverage/regression/**/coverage.cobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'
  
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Deploy to Testing Environment
        # # Add deployment steps here, such as deploying to a testing environment
        # # Example: Use SSH or FTP to deploy to a testing server
        # # Note: Replace the placeholders with your deployment commands
        # run: |
        #   ssh user@example.com "cd /path/to/deployment && git pull origin release && dotnet publish -o published_folder"
        #   # Example: Restarting the application after deployment
        #   ssh user@example.com "sudo systemctl restart your-application.service"
        run: echo "Deployment to testing environment completed successfully!"